### PR TITLE
build: Modernize build system

### PR DESCRIPTION
**Pull request by dongahn**
- Delete bundled packages (libgcrypt, libgpg-error and boost);
- Delete resource manager configuration files to later move them to etc;
- Delete package specification files to later move them to etc;
- Remove generated/copied files from autotools such as Makefile.in (They will go to the distributation tarball though.);
- Move resource management config files and package specification files to the etc directory;
- Update README files and bootstrap options;
- Update configure.ac;
- Update and add m4 files under config;
- Update automake files, Makefile.am.

Note that the intermediate commits will not build because a deep surgery is needed
for this modernization, and I didn't want to add all changes to a single commit either.

The final commit should build. But more testing will be needed to tag a commit for a release.

### CODE REVIEW

**Comment by dongahn** [comment]
@lee218llnl: as we discussed the other day, if you can review this PR, that's be great! This is a part of a solution to Issue #12

**Comment by lee218llnl** [comment]
I will have to look at the changes more closely, but I can tell you this configures and builds properly for me on a TOSS 3 system (hype2)!

**Comment by lee218llnl** [comment]
Not a huge deal, but you may want to updated your .gitignore for some of the bootstrap-generated files:

        Makefile.in
        config/aclocal.m4
        config/compile
        config/config.guess
        config/config.sub
        config/depcomp
        config/install-sh
        config/libtool.m4
        config/ltmain.sh
        config/ltoptions.m4
        config/ltsugar.m4
        config/ltversion.m4
        config/lt~obsolete.m4
        config/missing
        configure
        etc/Makefile.in
        etc/pkg-specs/Makefile.in
        etc/pkg-specs/llnl/Makefile.in
        launchmon/Makefile.in
        launchmon/man/Makefile.in
        launchmon/src/Makefile.in
        launchmon/src/linux/Makefile.in
        launchmon/src/linux/lmon_api/Makefile.in
        test/Makefile.in
        test/src/Makefile.in
        tools/Makefile.in
        tools/alps/Makefile.in
        tools/alps/src/Makefile.in
        tools/ciod/Makefile.in
        tools/cobo/Makefile.in
        tools/cobo/src/Makefile.in
        tools/handshake/Makefile.in

**Comment by lee218llnl** [comment]
Also not a big deal, but I see from configure --help that there is a "--without-gcrypt" option, but that LMON won't build if you specify this.

**Comment by lee218llnl** [comment]
Also, is there a way to configure without building tests?  I know with STAT sometimes folks want to build without requiring MPI.

**Comment by dongahn** [comment]
This should be possible. Let me look into this.

**Comment by dongahn** [comment]
> Also not a big deal, but I see from configure --help that there is a "--without-gcrypt" option, but that LMON won't build if you specify this.

Ah. This is probably  a side effect of using the canned gcrypt m4 macro. Let me look into this as well.

**Comment by dongahn** [comment]
In a similar vein, I also have `--with-bootfabric` option, which allows one to build LaunchMON's communication fabric based on MPI instead of COBO. But in general, building it with MPI is not a good idea for various reasons. 

Any objection, if I remove --with-bootfabric option and always build LaunchMON w/ COBO?

**Comment by lee218llnl** [comment]
> Any objection, if I remove --with-bootfabric option and always build LaunchMON w/ COBO?

No objection from me.

**Comment by dongahn** [comment]
> Also, is there a way to configure without building tests? I know with STAT sometimes folks want to build without requiring MPI.

OK. I looked into this a bit. How about:

- `make` will only make the main launchmon binaries and libraries, not the tests
- `make install` will install them, but not the test codes and scripts
- `make check` will build the tests and test scripts. For the long run, I need to hook this into an automatic testing rig, but for now it should be straightforward to make the check target to build the tests

If we do this, because the MPICC dependency is only for the check target, `make` will succeed without MPI. If you want to build and run some tests, you need MPI test programs so it makes sense to fail `make check` when ./configure cannot find a proper mpi compiler wrapper. 

For this, I'd like to pull in @tgamblin's `lx_find_mpi.m4` to replace the current dump mpicc detection logic. This macro can fail `%make check` with a bit better clue (`not-found`) when mpicc is not found. E.g., my test on hype2 without `module load openmpi-gnu/1.10` shows

```
% make check
<CUT>

not-found -DHAVE_CONFIG_H -I. -I../../../test/src -I../.. -I../../../launchmon/src -I../../../launchmon/src -I../../../launchmon/src/linux  -I../../../launchmon/src/linux/lmon_api   -g -O2 -o run_3mins ../../../test/src/run_3mins.c	
make[3]: not-found: Command not found
make[3]: *** [run_3mins] Error 127
make[3]: Leaving directory `/nfs/tmp2/dahn/LaunchMON-20160428/LaunchMON/build/test/src'
make[2]: *** [check-am] Error 2
make[2]: Leaving directory `/nfs/tmp2/dahn/LaunchMON-20160428/LaunchMON/build/test/src'
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory `/nfs/tmp2/dahn/LaunchMON-20160428/LaunchMON/build/test'
make: *** [check-recursive] Error 1
```

**Comment by dongahn** [comment]
OK I just forced a push. 

- Added more files/patterns in .gitignore
- Tests are only built with the check target (not normal build and install targets)
- Pulled in @tgamblin's `lx_find_mpi.m4`
- Simplified gcrypt and cobo configuration

However, this isn't yet ready for another review. If I find some time tomorrow, I will make it so that in-tree tests can run not only against the installed launchmon but also in-tree launchmon

**Comment by dongahn** [comment]
@lee218llnl: 
I believe this can use another review. Can you please take a look the latest changes and let me know what else you want me to address as part of this PR? The last commits add `--with-test-installed` support. 

BTW, while I was testing the latest changes, I found that launchmon tests won't run on TOSS3 systems. I don't know why yet and will spend some time on that issue so that we can finish up TCE packaging. But I propose we do this as a separate PR once this PR gets merged in. Thanks!

**Comment by dongahn** [comment]
BTW, there are some intermediate commits in this PR (two commits that change ChangeLog). If you want me to squash them, just let me know. At the expense of changing revision histories, we will have cleaner commit history.

**Comment by lee218llnl** [comment]
The build system looks mostly good to me. One thing I noticed is that a make dist creates an oddly versioned file "launchmon-5929619.tar.gz". 

I was able to run test_attach_1 on opal. I did a module load of mvapich2-v2.2-gnu. The test_launch_1 appears to hang.

**Comment by dongahn** [comment]
The odd number should be okay for now. Once I will add an annotated release version tag, it will use that tag instead of the SHA1.

Yes the hang you see on opal is the one that I referred to. I will get to that once this gets merged.

Sounds like pushing the merge button?

Dong


________________________________

**Pull request merged**
