### PR TITLE
Add support for Flux

### PR DESCRIPTION
**Pull request by dongahn**
This PR is work in process. This has preliminary support for Flux (https://github.com/flux-framework/flux-core).

- Add tool daemon launching helper script for Flux which use `flux exec` to launch the specified tool daemon launch string alongside the target parallel processes

- Add configuration files for Flux (`rm_flux.conf`) and integrate that into `rm_info.conf`

- Widen the data type to represent the jobid of the target (e.g., `totalview_jobid`) to 64-bit integer (`int64_t`).

- Map the process management semantics of Flux to that of LaunchMON to normalize how the upper layer of Flux handles the parallel processes spawned by Flux

- Adjust test cases for attach mode using `flux mini submit` and `flux job attach --debug` commands.

- Other misc. changes including fixing trailing whitespaces and indentation issues.

This requires my PR to flux-core () to be reviewed and merged.

I also need to get @agontarek's review for commit 87a413b.

I installed this version on LLNL TOSS machines so that STAT can be tested:

I configured LaunchMON with the following:
 
./configure --prefix=/collab/usr/global/tools/launchmon/toss_3_x86_64_ib/launchmon-flux --with-test-rm=flux --with-test-rm-launcher=/usr/global/tools/flux/toss_3_x86_64_ib/flux-c0.18.0-s0.10.0+tvjobid/bin/flux --enable-verbose=/usr/global/tools/launchmon/toss_3_x86_64_ib-logs/launchmon-flux --enable-debug --with-test-nnodes=2 --with-test-ncore-per-CN=36
 
If you want to try a simple example interactively (on a machine like rzgenie):
 
```
salloc -N 2 -n72 -ppdebug
srun -N 2 -n 2 --pty --mpi=none --mpibind=off /usr/global/tools/flux/toss_3_x86_64_ib/flux-c0.18.0-s0.10.0+tvjobid/bin/flux start
 
# once you get your interactive shell
cd /collab/usr/global/tools/launchmon/build/toss_3_x86_64_ib/LaunchMON/test/src
 
./test.attach_1
1597366471.138948 start
<Aug 13 17:54:51> <LMON FE API> (INFO): GCRYPT shared_key: 2022050527
<CUT>
[LMON FE] Please check the correctness of the following proctable
[LMON FE] host_name: rzgenie23
[LMON FE] executable_name: /collab/usr/global/tools/launchmon/build/toss_3_x86_64_ib/LaunchMON/test/src/hang_on_SIGUSR1
[LMON FE] pid: 1656(rank 0)
```

### CODE REVIEW

**Comment by dongahn** [comment]
Known issues to resolve:

- `test.attach_4_shutdownbe` doesn't completely work. We use `tools/flux/flux-helper.sh` (bash script) to bulk launch the tool daemons and we need to kill this process sufficiently good enough (a.k.a. kill support) so that `flux exec` used in the script gets killed as well. `rm_flux.conf` is configured to send two consecutive `SIGINT`s to this process but bash wouldn't be killed. Here, the way the signal is sent which is essentially equivalent to `kill -INT <PID of flux-helper.sh>` but this isn't good enough. If this were `kill -INT -PID` (note minus PID), I think this would kill both `flux-helper.sh` and `flux exec` processes sufficiently. But this can have other side effects since this will send `SIGINT` to the group that share the terminal. So I decide to revisit this later as part of hardening. The way we do bulk launch with Flux may change as well. Please see https://github.com/flux-framework/flux-core/issues/3110#issuecomment-668893081.

- No attempt was made to add support launch mode including porting test codes.

- Had mild levels of testing to make sure this doesn't break other resource managers like SLURM. But we need whole lot more. (Really need CI).

**Comment by dongahn** [comment]
From CI:

> ../configure: line 4134: syntax error near unexpected token `1.2.0,'
14822../configure: line 4134: `AM_PATH_LIBGCRYPT(1.2.0,'
14823The command "../configure --with-test-rm=orte $ARGS --with-test-rm-launcher=$HOME/local/bin/mpirun --with-test-ncore-per-CN=2 --with-test-nnodes=1" exited with 2.
148240.00s$ eval ${MAKECMDS}
14825make: *** No targets specified and no makefile found.  Stop.
14826The command "eval ${MAKECMDS}" exited with 2.

Should be an easy fix, I think.

**Comment by lee218llnl** [comment]
@dongahn #53 should fix the CI error about AM_PATH_LIBGCRYPT, so you may want to retrigger the check based on the current master.

**Comment by dongahn** [comment]
Yeah this needs to be rebased. We can enable mergifyio (https://mergify.io) to help w/ manual rebasing would be easiest.

**Comment by lee218llnl** [comment]
@dongahn do you think this is ready to merge? If so, I can give it a look over and merge.

**Comment by lee218llnl** [comment]
Merging despite known issues, will create issue with pending items.

**Pull request merged**
