### PR TITLE
add option to install tests

### PR DESCRIPTION
**Pull request by lee218llnl**
This will install tests if --with-install-tests and --with-test-installed are both specified.

### CODE REVIEW

**Comment by lee218llnl** [comment]
@dongahn mind taking a quick look at this?

**Comment by dongahn** [comment]
Thank you for working on this Greg!

I know you and I exchanged emails about this and I say your proposal was good. But now that I see your PR, I have one more feedback. 

Is there anyway whether `--with-test-installed` is given or not at config time? As is, the config will pass and the right makefile will not be generated if `--with-test-installed` is not given.

I understand you worry the order in which those config options are given, which makes it difficult to add this as a config time check. Perhaps, the new test can be a part of `X_AC_TEST_INSTALLED` to make it easy as a config time check.

One trick I can think about is to make `--with-test-installed` take three different values. "yes", "no" or "install-tests". And "install-test" or similar is given, "yes" is implied and also install tests as part of that?

**Comment by lee218llnl** [comment]
@dongahn Please let me know what you think of the latest squashed commit. Thanks.

**Comment by dongahn** [comment]
LGTM. One last check: does the long description appears clean with `./configure --help`? If so, this can go in.

**Comment by lee218llnl** [comment]
Yup, format's OK:

```
  --with-test-mw-hostlist[=host1:host2]
                          specify the list of hosts that middleware testing
                          should use
  --with-test-installed   set to "yes" to configure tests on installed
                          launchmon and set to "install-tests" to install
                          tests binaries and scripts. "install-tests" implies
                          "yes."
  --with-pic[=PKGS]       try to use only PIC/non-PIC objects [default=use
                          both]
```

**Pull request merged**
